/**
 * Curated fallback puzzles — used when Musixmatch API is unavailable.
 * 30 iconic tracks with hand-crafted clues for all 5 stages.
 */

export interface CuratedSong {
  id: number;
  trackName: string;
  artistName: string;
  albumName: string;
  spotifyTrackId: string | null;
  releaseYear: number;
  themes: string[];
  mood: string;
  obscureClue?: string;
  translatedLine: string;
  translationLanguage: string;
  translationLanguageCode: string;
  snippet: string;
  snippetWords: string[];
}

export const CURATED_SONGS: CuratedSong[] = [
  {
    id: 1001,
    trackName: "Blinding Lights",
    artistName: "The Weeknd",
    albumName: "After Hours",
    spotifyTrackId: "0VjIjW4GlUZAMYd2vXMi3b",
    releaseYear: 2019,
    themes: ["longing", "night drive", "desperation", "neon"],
    mood: "Euphoric",
    obscureClue: "Feels like flooring it through a city that never forgives, convinced one text back could turn the whole skyline holy. Neon-sweaty desperation, but make it ecstatic.",
    translatedLine: "No puedo dormir hasta que sienta tu toque",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I can't sleep until I feel your touch",
    snippetWords: ["I", "can't", "sleep", "until", "I", "feel", "your", "touch"],
  },
  {
    id: 1002,
    trackName: "Shape of You",
    artistName: "Ed Sheeran",
    albumName: "÷ (Divide)",
    spotifyTrackId: "7qiZfU4dY1lWllzX7mPBI3",
    releaseYear: 2017,
    themes: ["attraction", "body", "romance", "nightlife"],
    mood: "Playful",
    obscureClue: "The exact energy of locking eyes across a sticky dance floor and immediately forgetting your better judgment. Flirty, physical, and one wink away from a bad decision.",
    translatedLine: "Estoy enamorado de la forma de tu cuerpo",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I'm in love with the shape of you",
    snippetWords: ["I'm", "in", "love", "with", "the", "shape", "of", "you"],
  },
  {
    id: 1003,
    trackName: "Bohemian Rhapsody",
    artistName: "Queen",
    albumName: "A Night at the Opera",
    spotifyTrackId: "7tFiyTwD0nx5a1BI5eLmEc",
    releaseYear: 1975,
    themes: ["tragedy", "confession", "fate", "opera"],
    mood: "Dramatic",
    obscureClue: "Like confessing everything in the middle of a thunderstorm while the orchestra refuses to calm down. A beautiful disaster in formalwear, already doomed by intermission.",
    translatedLine: "¿Es esto la vida real? ¿Es esto solo fantasía?",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Is this the real life? Is this just fantasy?",
    snippetWords: ["Is", "this", "the", "real", "life?", "Is", "this", "just", "fantasy?"],
  },
  {
    id: 1004,
    trackName: "Rolling in the Deep",
    artistName: "Adele",
    albumName: "21",
    spotifyTrackId: "4b9ET1HfTVtaobWUeJFDiK",
    releaseYear: 2010,
    themes: ["betrayal", "heartbreak", "anger", "fire"],
    mood: "Fierce",
    obscureClue: "Post-breakup rage with the energy of deleting photos, blocking numbers, and mentally keying a car you'll never actually touch. Petty? Maybe. Cathartic? Absolutely volcanic.",
    translatedLine: "Podríamos haberlo tenido todo",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "We could have had it all",
    snippetWords: ["We", "could", "have", "had", "it", "all"],
  },
  {
    id: 1005,
    trackName: "Happy",
    artistName: "Pharrell Williams",
    albumName: "G I R L",
    spotifyTrackId: "60nZcImufyMA1MKQY3dcCH",
    releaseYear: 2013,
    themes: ["joy", "sunshine", "freedom", "positivity"],
    mood: "Joyful",
    obscureClue: "The soundtrack for rolling the windows down, forgiving the group chat, and deciding today is simply too bright for misery. Pure serotonin in outdoor voice.",
    translatedLine: "Porque soy feliz, aplaude si sientes que la felicidad es la verdad",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Because I'm happy, clap along if you feel like happiness is the truth",
    snippetWords: ["Because", "I'm", "happy,", "clap", "along", "if", "you", "feel"],
  },
  {
    id: 1006,
    trackName: "Someone Like You",
    artistName: "Adele",
    albumName: "21",
    spotifyTrackId: "1zwMYTA5nlNjZxYrvBB2pV",
    releaseYear: 2011,
    themes: ["heartbreak", "acceptance", "memory", "goodbye"],
    mood: "Melancholic",
    obscureClue: "That quiet moment after the crying stops and you realize the memory hurts less than the silence. Not healed, just finally able to fold the sweater and put it away.",
    translatedLine: "Nevermind, lo encontraré alguien como tú",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Never mind, I'll find someone like you",
    snippetWords: ["Never", "mind,", "I'll", "find", "someone", "like", "you"],
  },
  {
    id: 1007,
    trackName: "Counting Stars",
    artistName: "OneRepublic",
    albumName: "Native",
    spotifyTrackId: "2tpWsVSb9UEmDRxAl1zhX1",
    releaseYear: 2013,
    themes: ["dreams", "money", "faith", "ambition"],
    mood: "Hopeful",
    obscureClue: "A vision-board anthem for anyone who's prayed in a cramped room and still dressed like the penthouse was inevitable. Hope with receipts pending.",
    translatedLine: "Últimamente estoy perdiendo el sueño soñando con las cosas que podríamos ser",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Lately I been losing sleep dreaming about the things that we could be",
    snippetWords: ["Lately", "I", "been", "losing", "sleep", "dreaming", "about", "the", "things"],
  },
  {
    id: 1008,
    trackName: "Radioactive",
    artistName: "Imagine Dragons",
    albumName: "Night Visions",
    spotifyTrackId: "69yfbpvmkzlFnFoUHcHXeR",
    releaseYear: 2012,
    themes: ["power", "apocalypse", "awakening", "revolution"],
    mood: "Intense",
    obscureClue: "Sounds like the moment the crowd realizes the old world is on fire and starts dancing harder anyway. End-times cinema with a pulse and a manifesto.",
    translatedLine: "Despertando en las cenizas",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I'm waking up, I feel it in my bones",
    snippetWords: ["I'm", "waking", "up,", "I", "feel", "it", "in", "my", "bones"],
  },
  {
    id: 1009,
    trackName: "Chandelier",
    artistName: "Sia",
    albumName: "1000 Forms of Fear",
    spotifyTrackId: "4pMPGKmKdKSMHVnDGRIPaO",
    releaseYear: 2014,
    themes: ["excess", "escape", "party", "vulnerability"],
    mood: "Desperate",
    obscureClue: "A party so loud it almost drowns out the very private collapse happening behind your sunglasses. Champagne-as-bandage energy, glamorous until it isn't.",
    translatedLine: "Me balancearé desde la araña, voy a vivir como si mañana no existiera",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I'm gonna swing from the chandelier",
    snippetWords: ["I'm", "gonna", "swing", "from", "the", "chandelier"],
  },
  {
    id: 1010,
    trackName: "All of Me",
    artistName: "John Legend",
    albumName: "Love in the Future",
    spotifyTrackId: "3U4isOIWM3VvDubwSI3y7a",
    releaseYear: 2013,
    themes: ["devotion", "love", "imperfection", "surrender"],
    mood: "Tender",
    obscureClue: "Like loving someone enough to stop pretending either of you is a polished movie version of a person. Soft, flawed devotion with both hands up.",
    translatedLine: "Todo de mí ama todo de ti",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "All of me loves all of you",
    snippetWords: ["All", "of", "me", "loves", "all", "of", "you"],
  },
  {
    id: 1011,
    trackName: "Shake It Off",
    artistName: "Taylor Swift",
    albumName: "1989",
    spotifyTrackId: "5AnIoun13bkl9UQJtCK7PZ",
    releaseYear: 2014,
    themes: ["resilience", "haters", "carefree", "dancing"],
    mood: "Energetic",
    obscureClue: "For dancing like the haters paid admission and you intend to give them a full show. Unbothered cardio with glitter on it.",
    translatedLine: "Los jugadores van a jugar y los que odian van a odiar",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "The players gonna play and the haters gonna hate",
    snippetWords: ["The", "players", "gonna", "play", "and", "the", "haters", "gonna", "hate"],
  },
  {
    id: 1012,
    trackName: "Hello",
    artistName: "Adele",
    albumName: "25",
    spotifyTrackId: "4sPmO7WMQUAf45kwgCIn5n",
    releaseYear: 2015,
    themes: ["regret", "distance", "longing", "apology"],
    mood: "Nostalgic",
    obscureClue: "The emotional equivalent of typing a paragraph at 1:13 a.m., deleting half of it, and still hoping they somehow feel the rest. Distance makes every apology echo.",
    translatedLine: "Hola desde el otro lado",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Hello, it's me, I was wondering if after all these years you'd like to meet",
    snippetWords: ["Hello,", "it's", "me,", "I", "was", "wondering", "if", "after", "all"],
  },
  {
    id: 1013,
    trackName: "Stressed Out",
    artistName: "Twenty One Pilots",
    albumName: "Blurryface",
    spotifyTrackId: "3CRDbSIZ4r5MsZ0YwxuEkn",
    releaseYear: 2015,
    themes: ["nostalgia", "anxiety", "growing up", "childhood"],
    mood: "Wistful",
    obscureClue: "Feels like opening an old bedroom drawer and finding your childhood staring back with terrible timing. Growing up is weird when the ghosts are just former versions of you.",
    translatedLine: "Desearía poder volver a cuando tenía un corazón más joven",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I wish I found some better sounds no one's ever heard",
    snippetWords: ["I", "wish", "I", "found", "some", "better", "sounds", "no", "one's", "ever", "heard"],
  },
  {
    id: 1014,
    trackName: "7 Years",
    artistName: "Lukas Graham",
    albumName: "Lukas Graham",
    spotifyTrackId: "7129PkB9kQBuAj6xHKhVSF",
    releaseYear: 2015,
    themes: ["life stages", "family", "legacy", "reflection"],
    mood: "Reflective",
    obscureClue: "A living-room-at-dusk song where generations blur together and everyone suddenly has your father's hands. Tender inventory of what time keeps and steals.",
    translatedLine: "Una vez tuve siete años, mi mamá me dijo que creciera",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Once I was seven years old, my mama told me go make yourself some friends",
    snippetWords: ["Once", "I", "was", "seven", "years", "old,", "my", "mama", "told", "me"],
  },
  {
    id: 1015,
    trackName: "Budapest",
    artistName: "George Ezra",
    albumName: "Wanted on Voyage",
    spotifyTrackId: "7L6YYqBVFT6PVNK2wKZRaZ",
    releaseYear: 2014,
    themes: ["sacrifice", "love", "travel", "giving up everything"],
    mood: "Romantic",
    obscureClue: "The kind of romance that would absolutely sell the furniture, miss the flight, and call it destiny. Love as a passport stamp and a reckless financial decision.",
    translatedLine: "Mi casa te la daría si me lo pidieras",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "My house in Budapest, my hidden treasure chest",
    snippetWords: ["My", "house", "in", "Budapest,", "my", "hidden", "treasure", "chest"],
  },
  {
    id: 1016,
    trackName: "Photograph",
    artistName: "Ed Sheeran",
    albumName: "X (Multiply)",
    spotifyTrackId: "1nJvji2KIlWSseXRSlNYsC",
    releaseYear: 2014,
    themes: ["distance", "memory", "love", "time"],
    mood: "Tender",
    obscureClue: "Like two people trying to outlast geography with memory alone. Gentle proof that distance can shrink everything except what matters.",
    translatedLine: "Guardando el amor en una fotografía",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Loving can hurt sometimes, but it's the only thing that I know",
    snippetWords: ["Loving", "can", "hurt", "sometimes,", "but", "it's", "the", "only", "thing"],
  },
  {
    id: 1017,
    trackName: "Perfect",
    artistName: "Ed Sheeran",
    albumName: "÷ (Divide)",
    spotifyTrackId: "0tgVpDi06FyKpA1z0VMD4v",
    releaseYear: 2017,
    themes: ["love", "dancing", "devotion", "forever"],
    mood: "Romantic",
    obscureClue: "Wedding-dance devotion with the kind of certainty that makes strangers believe in soulmates for four minutes. Love in its best suit, spinning under cheap lights.",
    translatedLine: "Querida, eres perfecta para mí",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I found a love for me, darling, just dive right in and follow my lead",
    snippetWords: ["I", "found", "a", "love", "for", "me,", "darling,", "just", "dive"],
  },
  {
    id: 1018,
    trackName: "Believer",
    artistName: "Imagine Dragons",
    albumName: "Evolve",
    spotifyTrackId: "0pqnGHJpmpxLKifKRmU6WP",
    releaseYear: 2017,
    themes: ["pain", "strength", "transformation", "adversity"],
    mood: "Empowering",
    obscureClue: "Built like a comeback montage where every bruise gets promoted to character development. Pain walked in; power left wearing its coat.",
    translatedLine: "El dolor me hizo creyente",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "First things first, I'ma say all the words inside my head",
    snippetWords: ["First", "things", "first,", "I'ma", "say", "all", "the", "words", "inside"],
  },
  {
    id: 1019,
    trackName: "bad guy",
    artistName: "Billie Eilish",
    albumName: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    spotifyTrackId: "2Fxmhks0bxGSBdJ92vM42m",
    releaseYear: 2019,
    themes: ["dark humor", "subversion", "power", "irony"],
    mood: "Sly",
    obscureClue: "A smirk in song form — like making eye contact while flipping the script and the table. Darkly funny, slightly dangerous, and fully aware of the bit.",
    translatedLine: "Soy el chico malo, duh",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I'm the bad guy, duh",
    snippetWords: ["I'm", "the", "bad", "guy,", "duh"],
  },
  {
    id: 1020,
    trackName: "Dance Monkey",
    artistName: "Tones and I",
    albumName: "The Kids Are Coming",
    spotifyTrackId: "2XU0oxnq2qxCpomAAuJY8K",
    releaseYear: 2019,
    themes: ["performance", "control", "wonder", "raw talent"],
    mood: "Commanding",
    obscureClue: "The energy of someone grabbing the room by the collar and proving talent doesn't need permission. Half spectacle, half warning shot.",
    translatedLine: "Se mueven de manera que nunca he visto antes",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "They say oh my god I see the way you shine",
    snippetWords: ["They", "say", "oh", "my", "god,", "I", "see", "the", "way", "you", "shine"],
  },
  {
    id: 1021,
    trackName: "Watermelon Sugar",
    artistName: "Harry Styles",
    albumName: "Fine Line",
    spotifyTrackId: "6UelLqGlWMcVH1E5c4H7lY",
    releaseYear: 2019,
    themes: ["summer", "pleasure", "nostalgia", "sweetness"],
    mood: "Carefree",
    obscureClue: "Tastes like melted popsicles, sunscreen, and the kind of summer memory that gets more golden every year. Sweet, lazy, and impossible to hate.",
    translatedLine: "Azúcar de sandía alta",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I just wanna taste it, I just wanna taste it",
    snippetWords: ["I", "just", "wanna", "taste", "it,", "I", "just", "wanna", "taste", "it"],
  },
  {
    id: 1022,
    trackName: "drivers license",
    artistName: "Olivia Rodrigo",
    albumName: "SOUR",
    spotifyTrackId: "5wANPM4fQCJwkW6AIhigmM",
    releaseYear: 2021,
    themes: ["heartbreak", "suburban", "coming of age", "loss"],
    mood: "Devastated",
    obscureClue: "Feels like realizing the cul-de-sac can't protect you from real grief after all. Suburban innocence shattered somewhere between the driveway and adulthood.",
    translatedLine: "Y todavía conduzco con tu chaqueta en el asiento de atrás",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I drove to your street in the dead of night",
    snippetWords: ["I", "drove", "to", "your", "street", "in", "the", "dead", "of", "night"],
  },
  {
    id: 1023,
    trackName: "good 4 u",
    artistName: "Olivia Rodrigo",
    albumName: "SOUR",
    spotifyTrackId: "6PERP62TUjnqVTbKmMBOzK",
    releaseYear: 2021,
    themes: ["bitterness", "breakup", "rage", "moving on"],
    mood: "Sardonic",
    obscureClue: "A breakup song for when healing can wait because being hilariously bitter is way more fun tonight. Smiling through the eye roll counts as closure, actually.",
    translatedLine: "Qué bien para ti, supongo que te estás haciendo bien sin mí",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Well, good for you, I guess you moved on really easily",
    snippetWords: ["Well,", "good", "for", "you,", "I", "guess", "you", "moved", "on", "really"],
  },
  {
    id: 1024,
    trackName: "As It Was",
    artistName: "Harry Styles",
    albumName: "Harry's House",
    spotifyTrackId: "4Dvkj6JhhA12EX05fT7y2e",
    releaseYear: 2022,
    themes: ["change", "solitude", "truth", "time passing"],
    mood: "Bittersweet",
    obscureClue: "Like standing in a half-empty room after everyone leaves and finally hearing what your life has been trying to tell you. Solitude with better lighting and no easy answers.",
    translatedLine: "En este mundo ya no estás bien solo",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "In this world, it's just us, you know it's not the same as it was",
    snippetWords: ["In", "this", "world,", "it's", "just", "us,", "you", "know", "it's"],
  },
  {
    id: 1025,
    trackName: "Flowers",
    artistName: "Miley Cyrus",
    albumName: "Endless Summer Vacation",
    spotifyTrackId: "3AhXZa8sUQht0UEdBJgpGc",
    releaseYear: 2023,
    themes: ["self-love", "independence", "healing", "empowerment"],
    mood: "Triumphant",
    obscureClue: "The glow-up after the storm, when choosing yourself stops feeling selfish and starts feeling overdue. Victory lap energy in the mirror aisle.",
    translatedLine: "Puedo comprarme flores",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I can buy myself flowers, write my name in the sand",
    snippetWords: ["I", "can", "buy", "myself", "flowers,", "write", "my", "name", "in", "the", "sand"],
  },
  {
    id: 1026,
    trackName: "Stay With Me",
    artistName: "Sam Smith",
    albumName: "In the Lonely Hour",
    spotifyTrackId: "5RYjQEQ0OdQQzlPdUhExJA",
    releaseYear: 2014,
    themes: ["loneliness", "one night stand", "vulnerability", "craving"],
    mood: "Longing",
    obscureClue: "That 2 a.m. ache where you know this won't fix anything, but loneliness is persuasive in low light. Intimacy rented by the hour, longing kept forever.",
    translatedLine: "Oh, ¿por qué no puedes quedarte conmigo?",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Oh, won't you stay with me, 'cause you're all I need",
    snippetWords: ["Oh,", "won't", "you", "stay", "with", "me,", "'cause", "you're", "all", "I", "need"],
  },
  {
    id: 1027,
    trackName: "Riptide",
    artistName: "Vance Joy",
    albumName: "Dream Your Life Away",
    spotifyTrackId: "4ZJML5lCcHOEbNAHoHOOYD",
    releaseYear: 2013,
    themes: ["infatuation", "fear", "ocean", "supernatural"],
    mood: "Dreamy",
    obscureClue: "Like falling for someone so hard they start to feel mythological — beautiful, dangerous, maybe not entirely terrestrial. A crush drifting in on moonlit tide.",
    translatedLine: "Siempre te arrastraré hacia mí",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I was scared of dentists and the dark",
    snippetWords: ["I", "was", "scared", "of", "dentists", "and", "the", "dark"],
  },
  {
    id: 1028,
    trackName: "Royals",
    artistName: "Lorde",
    albumName: "Pure Heroine",
    spotifyTrackId: "4D7BCuvgdJlYvlX5WlN54t",
    releaseYear: 2013,
    themes: ["class", "aspiration", "realism", "pop culture"],
    mood: "Cool",
    obscureClue: "The cool-kid realism of wanting the glossy life while fully clocking the price tag. Pop culture daydreams in practical shoes.",
    translatedLine: "Nunca seremos realeza",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "I've never seen a diamond in the flesh",
    snippetWords: ["I've", "never", "seen", "a", "diamond", "in", "the", "flesh"],
  },
  {
    id: 1029,
    trackName: "Lose Yourself",
    artistName: "Eminem",
    albumName: "8 Mile",
    spotifyTrackId: "5Z01UMMf7V1o0MzF86s6WJ",
    releaseYear: 2002,
    themes: ["opportunity", "hustle", "nerve", "second chances"],
    mood: "Urgent",
    obscureClue: "Feels like your last clean shirt before a big interview and your whole future balancing on one brave lie. Scrappy, breathless, and allergic to wasting a shot.",
    translatedLine: "Una oportunidad, una vez en la vida",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "Look, if you had one shot or one opportunity to seize everything you ever wanted",
    snippetWords: ["Look,", "if", "you", "had", "one", "shot", "or", "one", "opportunity"],
  },
  {
    id: 1030,
    trackName: "Mr. Brightside",
    artistName: "The Killers",
    albumName: "Hot Fuss",
    spotifyTrackId: "003vvx7Niy0yvhvHt4a14Y",
    releaseYear: 2003,
    themes: ["jealousy", "paranoia", "obsession", "heartbreak"],
    mood: "Tortured",
    obscureClue: "The sound of reading too much into a pause, a look, a silence, a heartbeat. Jealousy turns the mind into a detective with no sleep and terrible evidence.",
    translatedLine: "Y nunca está en mi cabeza",
    translationLanguage: "Spanish",
    translationLanguageCode: "es",
    snippet: "It started out with a kiss, how did it end up like this",
    snippetWords: ["It", "started", "out", "with", "a", "kiss,", "how", "did", "it", "end", "up", "like", "this"],
  },
];

/** Returns today's curated song based on puzzle number */
export function getCuratedSong(puzzleNumber: number): CuratedSong {
  const idx = (puzzleNumber - 1) % CURATED_SONGS.length;
  return CURATED_SONGS[idx];
}

/** Search curated songs (for autocomplete fallback) */
export function searchCuratedSongs(query: string, limit = 8): CuratedSong[] {
  const q = query.toLowerCase().trim();
  if (!q) return CURATED_SONGS.slice(0, limit);

  const scored = CURATED_SONGS.map((song) => {
    const combined = `${song.trackName} ${song.artistName}`.toLowerCase();
    let score = 0;
    if (combined.includes(q)) score += 2;
    if (song.trackName.toLowerCase().startsWith(q)) score += 3;
    if (song.artistName.toLowerCase().startsWith(q)) score += 2;
    return { song, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, limit).map((x) => x.song);
}

/** Build richsync word timing from words array (400ms per word) */
export function buildRichsyncWords(
  words: string[],
  startMs = 15000,
  msPerWord = 450,
): Array<{ word: string; startMs: number; endMs: number }> {
  return words.map((word, i) => ({
    word,
    startMs: startMs + i * msPerWord,
    endMs: startMs + (i + 1) * msPerWord - 50,
  }));
}
